### PR TITLE
Version: 24.11.1: Feat/1 update questions

### PR DESCRIPTION
**Pull request by arunge**
# InquiryR 24.11.1

## New Features
- option to import and modify inquiry templates (#1)
  - set an inquiry _name_ and a _description_ 
  - add _standard_ questions as supported by `shinysurveys` package, see [vignette](https://shinysurveys.jdtrat.com/articles/surveying-shinysurveys.html)
  - remove questions from the template
  - edit cells of the questions data frame
- option to add a password before saving a template (#2)
  - the password is required to load the template: either to modify the template or to respond to the inquiry
  - when a password is set, the template is saved as an encrypted object; the download is a `raw` file instead of a `json` file
  - after import, the file is checked if it is encrypted and if so, the user must enter the password to load it

### CODE REVIEW

**Comment by arunge** [comment]
@f-lukas Could you please test the features described [above](https://github.com/Pandora-IsoMemo/InquiryR/pull/3#issue-2658324243)?

**Comment by f-lukas** [comment]
@arunge I did not look at the code yet but will do this later. The app is really cool. Here are two things that I have noticed.

- If you have created or imported a template and then click on the "Example" button. And then click on "Load" to load your own template again, the load button does not work anymore. If you can not reproduce it, let me know and I will show you.
- Do you know why there are three entries in the download file of the submitted answers?
Bildschirmfoto vom 2024-11-14 13-36-48

**Comment by f-lukas** [comment]
Another thing:

- I have created a yes no question but can not see yes/no in the submit form.
Bildschirmfoto vom 2024-11-14 13-51-20

**Review by f-lukas — COMMENTED** [review]
I like the structure of the code a lot. I could also follow the code really easily. The only thing I noticed was, that we need many observe calls in this app. You could further improve readibility by creating functions for the observe blocks. You did exactly this for `observeShowPassword(input, id_password = ns("password"))` and I think the code would benefit from doing this more often. But this is nothing you need to change now.

**Comment by arunge** [comment]
@f-lukas Thanks for checking!

Regarding:

> If you have created or imported a template and then click on the "Example" button. And then click on "Load" to load your own template again, the load button does not work anymore. If you can not reproduce it, let me know and I will show you.

I could reproduce it: a reset of a reactiveValues list was missing when loading the import, I added this. :heavy_check_mark: 

> Do you know why there are three entries in the download file of the submitted answers?

I updated this, now I use the function `shinysurveys::getSurveyData()` to aggregate the responses. :heavy_check_mark: 

> I have created a yes no question but can not see yes/no in the submit form.

I fixed the logic how options are created, now it should always work. :heavy_check_mark: 


> The app is really cool.
> I like the structure of the code a lot. I could also follow the code really easily.

:heart: 

All issues from above are solved. Feel free to test and approve. :blush:

**Review by f-lukas — APPROVED** [review]
Great, everything works now.

**Pull request merged**
